### ISSUE TITLE
[RFC] Editable fields depending on the stage

### ISSUE THREAD

**Issue by seb-elico** [OCA/business-requirement#101]
Currently, the fields of a BR are only editable when it's in Draft stage. It's conflicting with the workflow. As a reminder, here's the meaning of the stages:

- Draft: prepare the scope on the first tab (at least Customer Story)
- Confirmed: customer has confirmed the scope, we can finalize the solution (Scenario, Gap Analysis, QA) and estimate it (Deliverables + Resources)
- Approved: the solution and estimation has been approved internally, we can send it to the customer
- Stakeholder Approval: the customer has approved the estimation, we can start (i.e. generate) the project (we can still modify the assignee for each resource)
- In Progress: the project has started

Here's the matrix to summarize (`V` = editable, `X` = read-only):
````
              Draft  Confirmed  Approved  SH Appr.  In prog.
Cust. Story     V        X          X        X         X
Scenario        V        V          X        X         X
Gap             V        V          X        X         X
QA              V        V          X        X         X
Deliverables    V        V          X        X         X
Resources       V        V          X        X         X
Assignee        V        V          V        V         X
````

**Comment by seb-elico** [comment]
@elicoidal @victormartinelicocorp

**Comment by elicoidal** [comment]
:+1:
