### ISSUE TITLE
[RFC] Improve business_requirement_deliverable_project category management

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#102]
Task could have main Category by install https://github.com/OCA/project/tree/8.0/project_task_category

On business_requirement_deliverable_project when generate Task want to set this Category and create the Task with.

I would propose new module:

business_requierment_deliverable_project_main_category

depends on
business_requierment_deliverable_project 
and
project_task_category

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico Could review?

**Comment by elicoidal** [comment]
:+1:
