### ISSUE TITLE
Use etherpad, same as for the tasks description

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#110]
Instead of html editor, use etherpad, same feature as created for the tasks description, available for all 4 fields (CS/Sc/Gap/Test Case)

* Customer Story
* Scenario
* Gap
* Test Case

To be improved on base module BR or added on new module business_requirement_etherpad

**Comment by elicoidal** [comment]
@victormartinelicocorp 
thinking about it, what I am not sure is whether the output of Etherpad is compatible with the qweb report (lists, images, etc.)

**Comment by dreispt** [comment]
If you use Etherpad, make it an option.
I personally have security and privacy concerns about Etherpad, and prefer not to use it.

**Comment by elicoidal** [comment]
@dreispt It would a separate module (like the one for the tasks).
Anyway I am not sure it is compatible with qweb printing.

**Comment by dreispt** [comment]
AFAIK the Etherpad content is stored outside your DB, in the Etherpad server (hosted by Odoo SA?).
So I bet you won't be able to use it on QWeb.
Maybe it could be useful to have it alongside the the "official" HTML description, as a collaboration notepad.

**Comment by elicoidal** [comment]
@dreispt Actually it is not where it is stored (we have a server for that) but the format itself which is basically plain text.
I like the idea of collaborative pad available but I'd rather have system-wide for any object.
Maybe start with a simple field notes in etherpad for the moment ;)

**Comment by elicoidal** [comment]
Let's move forward with this topic altering the requirement as suggested:
* Add a field tab "Notes" (before logs) with a field notes link to Etherpad.
* Name of the module: business_requirement_etherpad
* Depends on etherpad and business_requirements

cc @dreispt @rubencabrera @seb-elico @victormartinelicocorp
