### ISSUE TITLE
List are not properly displayed in qweb report

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#111]
Here is the content of the field:

![screenshot from 2017-04-08 08-45-04](https://cloud.githubusercontent.com/assets/7600613/24824072/5f66995e-1c38-11e7-9ea5-a551c678db76.png)

The display on the qweb report is ugly and even misleading:

![screenshot from 2017-04-08 08-44-35](https://cloud.githubusercontent.com/assets/7600613/24824070/546bdca8-1c38-11e7-822d-53de5837eeff.png)

**Comment by elicoidal** [comment]
@victormartinelicocorp @sudhir-serpentcs

**Comment by elicoidal** [comment]
@victormartinelicocorp @sudhir-serpentcs @pedrobaeza @dreispt @sbidoul any idea?

Is this behavior normal or can we fix it?

**Comment by sbidoul** [comment]
@elicoidal no idea. Try opening the report in HTML mode and looking at the exact html markup that is generated.

**Comment by elicoidal** [comment]
@sudhir-serpentcs any idea how to solve this?

**Comment by sudhir-serpentcs** [comment]
@elicoidal  @victormartinelicocorp 
fixed in qweb-report
is it perfect!
![screenshot from 2017-06-14 18-14-19](https://user-images.githubusercontent.com/13166978/27132720-873c9968-512d-11e7-81af-791c29cddba0.png)
