### ISSUE TITLE
BR def name_get() Issue when use Group By on Task by business-requirement

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#114]
BR name_get use format() built in Python lib and if some string is unicode will happen like this:

Apr 11 10:44:25 superman docker/trunk_odoo-elico_1[806]:   File "/opt/odoo/additional_addons/business-requirement/business_requirement/models/business.py", line 256, in name_get
Apr 11 10:44:25 superman docker/trunk_odoo-elico_1[806]:     formatted_name = '[{}] {}'.format(br.name, br.description)
Apr 11 10:44:25 superman docker/trunk_odoo-elico_1[806]: UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-37: ordinal not in range(128

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico

**Comment by seb-elico** [comment]
@victormartinelicocorp maybe you can try with the `%` substitution

**Comment by martintorresvm** [comment]
Yes indeed it's need to be changed by another method. I will create an Issue as well for us. 
Here I need @elicoidal add the tags `bug` and `help wanted`
