### ISSUE TITLE
[8.0] business_requirement_deliverable need to be consisten when DL and RL are related

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#125]
Because now RL and DL could be independent but if they are related between then should belong to same BR.
1) FIX

On the Resource Lines Form and Tree view should be not possible edit business_requirement_id

If business_requirement_deliverable_id is set

Add domain on Views to fix

readonly="{'business_requirement_deliverable_id', '!=', False}

2) FIX

On the Form Deliverable

if the business_requirement_id is edit then

should be updated the business_requirement_id on the related Resource Lines

**Comment by elicoidal** [comment]
fixed by #126
