### ISSUE TITLE
[8.0] Onchange product_id in deliverable.

### ISSUE THREAD

**Issue by rubencabrera** [OCA/business-requirement#127]
This onchange might be a bit annoying when we come with context from another model and are creating a deliverable on the fly. If, from context, we had a description, and select a product, it replaces our text. If we change opinion and delete the selected product, we end up with an empty description, which is even more inconvenient, IMHO.

Is it ok if I create a PR to change this behavior? Any comments on anything I haven't thought of?

**Comment by martintorresvm** [comment]
onchange the product then should place the description only if that moment is empty.

Is what you mean?

**Comment by rubencabrera** [comment]
That would be what I'd expect, are you ok with it?

**Comment by elicoidal** [comment]
@rubencabrera thanks for the proposal: looks like a good idea.
Be careful: the onchange should continue triggering modifications for prices etc.

**Comment by elicoidal** [comment]
fixed by #132
