### ISSUE TITLE
[8.0] 'business.requirement.resource' object has no attribute 'price_total'

### ISSUE THREAD

**Issue by rubencabrera** [OCA/business-requirement#128]
The price_total field is (now) defined in the module business_requirement_deliverable_cost, which is not a dependency of business_requirement_deliverable, [where the field is referenced](https://github.com/OCA/business-requirement/blob/8.0/business_requirement_deliverable/models/business.py#L321).

**Comment by martintorresvm** [comment]
Indeed is an issue. We need to decide if remove from calculation or add on **business_requirement_deliverable**

cc @elicoidal @seb-elico

**Comment by elicoidal** [comment]
This is indeed not correct. It should be the sum of the costs in this part of the code.
To be fixed.
@rubencabrera thanks for pointing out!

**Comment by elicoidal** [comment]
@rubencabrera 
We are stabilizing the new version of the modules and somehow the cost and revenue fields got messed up: it will be fixed on Monday.
We are doing now integration testing with our current database (with 1000 Business Requirement database) so we will be able to spot some more in the coming days.
All in all I hope that by end of next week everything is (finally stable)

**Comment by elicoidal** [comment]
Fixed by #131
