### ISSUE TITLE
[RFC] Migration Path

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#133]
A migration process was started a long time ago from v8 to v9.
In the meantime the whole structure of the files and strong improvements have been added to the v8 version of the module and v9 migration has been stopped.
Today the version of v8 is now stabilized and we will restart the migration process.
Current code is v9 is obsolete so I am wondering about the best course of action:
* Option 1: We continue the current migration process and fix the current module even if the changes are steep
* Option 2:  Reinitialize the v9 / v10 repo following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#initialization-already-done-in-oca and restart the job from the newest and cleanest version 8 set of modules

@dreispt @pedrobaeza @sudhir-serpentcs @seb-elico @victormartinelicocorp

**Comment by elicoidal** [comment]
#20 #48

**Comment by pedrobaeza** [comment]
As these objects only have some connections with the rest of the system, I think it's simpler to start from 8.0 and change again the code that links with the rest seeing what it has been done on current v9 PRs.

**Comment by elicoidal** [comment]
(seems like option 2)
I have the same feelings unfortunately

**Comment by seb-elico** [comment]
@elicoidal to be noted that #115 is still on hold, I would suggest to wait until it's done before re-starting the migration.

**Comment by elicoidal** [comment]
agree

**Comment by elicoidal** [comment]
Branch 9.0 and 10.0 have been reintialized from the latest v8 set of modules
