### ISSUE TITLE
Task smart button does not display BR related task (displays all tasks now)

### ISSUE THREAD

**Issue by fausthuang** [OCA/business-requirement#141]
Currently, in BR screen, if we click the task smart button, it will not list the tasks related with this BR, but all tasks will be list.  
actually, should just show this BR's tasks.

**Comment by elicoidal** [comment]
Actually not sure: we cannot reproduce in Runbot so maybe this is a local issue.

**Comment by rubencabrera** [comment]
Happened to me too, but seems to be fixed on 8.0

**Comment by rubencabrera** [comment]
I cannot reproduce this anymore, can you confirm the problem persists and give a bit more insight on which modules you have installed?

**Comment by elicoidal** [comment]
We have the issue in our ERP but cannot reproduce it here. 
I think this is linked to another module so I will close this issue here and open it privately
