### ISSUE TITLE
In stages missing the stage "drop"

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#144]
We need 2 stages like in previous version:
* Cancel: the demand is irrelevant/erroneous
* Drop: decision is made not to pursue the BR

Currently only one (Cancel)

**Comment by elicoidal** [comment]
Actually the stage exists and can be used in kanban view but does not appear in the form view

**Comment by elicoidal** [comment]
@darshan-serpent

**Comment by serpentcs-dev1** [comment]
Okay let me check
