### ISSUE TITLE
Cannot change assignee in Resource lines in Stakeholder approval stage

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#145]

**Comment by elicoidal** [comment]
@darshan-serpent

**Comment by serpentcs-dev1** [comment]
I guess I missed this, will continue to work on this.

**Comment by serpentcs-dev1** [comment]
@elicoidal Here in RL we need state field from BR to make them readonly / editable. So I guess, we should create a related field of **state** of BR and use it in XML in attrs.

Let me know this is a right way to do this or there is any other way to achieve this functionality.

**Comment by elicoidal** [comment]
It is reasonable to have in RL  information related/stored (depending) from the BR (customer, state, pricelist etc.)
So for me :+1:
