### ISSUE TITLE
Field Linked project should be readonly

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#146]

**Comment by rubencabrera** [comment]
Isn't it already readonly? It's only editable on draft state, both on business_requirement and business_requirement_deliverable models. It seems to work as defined on my test db, can you give more detail to reproduce?

**Comment by elicoidal** [comment]
@rubencabrera even in draft state it should be read only.
This field is be automatically filed in when we generate the project.

I don't think there is a need to let the user input manually that information: do you have use case that would support to keep it not read only in draft (or more stages)?

**Comment by rubencabrera** [comment]
I don't see the need for it to be editable, I also prefer the automatic link when generating project.

**Comment by elicoidal** [comment]
Thanks for your feedback. We will proceed then

**Comment by rubencabrera** [comment]
Should it be readonly too for the deliverable?

**Comment by elicoidal** [comment]
yes: although it is not visible in form view

**Comment by rubencabrera** [comment]
Fine, I assumed that, you can test the PR to see if it fits.

**Comment by elicoidal** [comment]
Fixed by #148
