### ISSUE TITLE
Unread mail filter doesnot work for BR

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#151]
Clicking on the unread sticker does not filter only by unread mails

**Comment by elicoidal** [comment]
@darshan-serpent

**Comment by serpentcs-dev1** [comment]
@elicoidal Strange as we tested on local and runbot it works fine.

This are the steps we followed
- Created a new BR.
- Send message from demo user for the same BR 
- And now the Admin user can see the BR with advanced search filter 'Unread Message'


![unread_filter](https://cloud.githubusercontent.com/assets/20109026/26550113/e421f2b8-4499-11e7-94ce-2114c9c2639a.png)

**Comment by elicoidal** [comment]
OK: we will have to investigate more internally why. I am closing for now this one
