### ISSUE TITLE
Search in RL for customer or project doesnot work

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#156]
@darshan-serpent

**Comment by serpentcs-dev1** [comment]
![with_space_customer1](https://cloud.githubusercontent.com/assets/20109026/26538760/588f0eb2-4466-11e7-82ca-75894713277f.png)

@elicoidal We checked the runbot and the search works fine on Customer and Project.

Also, make sure that you don't leave any whitespace in the front and the back, as while we were testing accidentally we also left one and we weren't able to receive the search result. 

@victormartinelicocorp

**Comment by elicoidal** [comment]
@darshan-serpent Thanks!
Closing this one: internal data migration issue.
