### ISSUE TITLE
By default, BR menu should display list view rather than Kanban

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#158]
@darshan-serpent

**Comment by serpentcs-dev1** [comment]
@elicoidal 

I checked BR menu which already displays list view by default. Can you please confirm?

![default_listview o](https://cloud.githubusercontent.com/assets/20109026/26619997/8c4cf626-45fe-11e7-8b7b-1c47d7f63fb9.png)

**Comment by elicoidal** [comment]
OK: was not the case in the past. Sorry for the noise
