### ISSUE TITLE
In BR form view, it should be possible to change the kanban state without editing the form

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#161]
@darshan-serpent

**Comment by elicoidal** [comment]
@darshan-serpent

**Comment by serpentcs-dev1** [comment]
Yes, I am working on it. Actually not able to find the reason maybe it needs a JS tweak.

**Comment by elicoidal** [comment]
It should be similar in behavior to the project or task widget no?

**Comment by serpentcs-dev1** [comment]
Yeah right tried to apply the same behavior but does not work in this case, strange!

No problem I'll double check it and fix it.

**Comment by serpentcs-dev1** [comment]
@elicoidal I was testing I found that the kanban_state stays non-editable if it is the inherited view.

But if I add the field `kanban_state` in business_requirement module it works smooth as silk.

**Comment by elicoidal** [comment]
@darshan-serpent thanks for the feedback!
Strange but if so then can you transfer the field accordingly?

**Comment by serpentcs-dev1** [comment]
Yes I would do that, just let try this and let's see how it looks on runbot, till then I'll try to also find the reason from the root.

**Comment by rubencabrera** [comment]
Someone please close so we don't keep checking it. Thanks @darshan-serpent for the PR!

**Comment by elicoidal** [comment]
Thanks for the follow up!
