### ISSUE TITLE
[business_requirement_deliverable_report] BR print report is not printing RL if not related to an DL

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#176]
Need to fix reports for print BR with DL and RL.

That will print at the end also the RL that has only reference to the BR.

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico

**Comment by elicoidal** [comment]
:+1:

**Comment by elicoidal** [comment]
@darshan-serpent

**Comment by serpentcs-dev1** [comment]
Okay, will try to reproduce and then will resolve the same.
