### ISSUE TITLE
[FIX] BR ordering on Tree view need to be fix

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#181]
As this line of code suggest:
https://github.com/OCA/business-requirement/blob/8.0/business_requirement/models/business.py#L13

The order when is displayed should correspond as:
`select * from business_requirement order by id desc, name desc;`

Actually the order is not according this expectation and confuse user when create a new BR.

**Comment by martintorresvm** [comment]
@seb-elico @elicoidal

**Comment by elicoidal** [comment]
Please see #180 
Order should be reverse the name (which honestly should be the same as id).
id being unique I dont see the point of the second sorting key anyway.
@victormartinelicocorp @seb-elico

**Comment by elicoidal** [comment]
Actually #180 is not working in Runbot so we are missing something

**Comment by seb-elico** [comment]
> id being unique I dont see the point of the second sorting key anyway.

@elicoidal :+1: 

> Actually #180 is not working in Runbot so we are missing something

I confirm
