### ISSUE TITLE
Add a button to copy the total revenue in Deliverable Lines

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#189]
Currently in the DL form view, the list of RL are providing an automatic calculation based on the resources and sales prices at RL level.
Total revenue at resource line level is displayed as a total.

For business reasons, this total is not updated automatically to the Deliverable lines: there might be multiple reasons not to apply the automatic calculation.

To ease though the data entry we suggest to add a button to copy on demand the total revenue calculated in the RL into the DL revenue.

**Comment by serpentcs-dev1** [comment]
@elicoidal 

So you need a button in the DL which will just sum the total revenue from all the RL and will propagate it to the DL's total revenue??

 Is this what you mean?

**Comment by elicoidal** [comment]
as simple as that yes. Only for the given deliverable.
@darshan-serpent

**Comment by serpentcs-dev1** [comment]
Still, one little thing to clear.

There's already a field in DL called Total Revenue, which right now is computed as `sale_price * qty`

So now... should we append the calculation of RL total revenue to the DL revenue field or totally should replace??

![deliverable lines odoo](https://user-images.githubusercontent.com/20109026/27818342-def02c08-60b2-11e7-8f76-5cd79571050f.png)

**Comment by elicoidal** [comment]
@darshan-serpent https://github.com/OCA/business-requirement/pull/211#issuecomment-312795556
I have clarified my initial requirement: it should update the Sales Price field.
Let me know if still unclear
