### ISSUE TITLE
Sorting is not possible anymore for the RL

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#190]
Resources lines cannot be sorted anymore by drag and drop in the following views:
* Product templates
* Deliverable Form view
* Resource Line tree View

**Comment by sudhir-serpentcs** [comment]
@Eric I checked the views and I am able to sort RLs in all 3 views you specified.

**Comment by elicoidal** [comment]
In Resource line/Treeview:OK for drag and drop.
In following screen there is no way to drag and drop (Deliverable):
![screenshot from 2017-06-30 18-50-07](https://user-images.githubusercontent.com/7600613/27732730-4736040e-5dc5-11e7-8329-0b44614811d9.png)


In following screen neither (template):
![screenshot from 2017-06-30 18-51-38](https://user-images.githubusercontent.com/7600613/27732736-50b95878-5dc5-11e7-9d65-e0f6c4b8f731.png)


Let me know if that is clear enough

**Comment by elicoidal** [comment]
@sudhir-serpentcs

**Comment by sudhir-serpentcs** [comment]
@elicoidal Is it related to drag-drop or sorting? The issue is for sorting the RLs but you said:
`In following screen there is no way to drag and drop (Deliverable)`
Can you please let me know whether I have to work for sorting or for drag-drop?

**Comment by elicoidal** [comment]
I think the wording is not clear .

Basically we should be able to:
1 create the template RL in the product
2. drag and drop to fix the right sequence for the template RL
3 import the RL using the deliverable with proper sorting fixed in 2
4. change if necessary the sequencing by drag and drop

@sudhir-serpentcs
