### ISSUE TITLE
[FIX] 8.0 Business Requirement states blank DL and RL smart button values 

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#191]
Business Requirement states blank DL and RL smart button values

On change the BR state from "Confirmed" to "Approved" it seems set 0 these values.

**Comment by martintorresvm** [comment]
@seb-elico @elicoidal

**Comment by elicoidal** [comment]
confirmed

**Comment by serpentcs-dev1** [comment]
@victormartinelicocorp @elicoidal I think this issue would be resolved now, as the above referred PR is merged. Could you please confirm/review??

**Comment by elicoidal** [comment]
@darshan-serpent We will update in production server and check with actual data
