### ISSUE TITLE
[RFC] Change string of Customer field to Partner/Stakeholder?

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#197]
As a BR can be both for internal project or commercial project, it is suggested to change the name of res.partner related field to
1. Partner or
2. Stakeholder

Not sure which one could be the more suitable

**Comment by elicoidal** [comment]
@lasley any advice as English speaking?

**Comment by lasley** [comment]
Just to make sure I'm clear on the field definition: This is representing the requestor/beneficiary of the business requirement's goal or end product?

If that's the case, Stakeholder is the best IMO

**Comment by elicoidal** [comment]
@lasley That is correct: it could be a customer or an internal department or whatever party that would benefit from the BR.
Thanks the for the confirmation: Stakehoder would make sense to me too (We have already a Stakeholder approval stage so it would become more consistent)

**Comment by elicoidal** [comment]
@sudhir-serpentcs @darshan-serpentcs Can you proceed?

**Comment by YogeshMahera-SerpentCS** [comment]
Shall I proceed? @elicoidal

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS Yes please
