### ISSUE TITLE
Refactor EVM report after #115

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#213]
#115 has changed the way the BR and the projects are linked together.
EVM should be refactored in order to take into account the new relationship between both models
@sudhir-serpentcs

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
#115 
I have tested the EVM report as per new relationship it's working fine. The changes are already complaint to the code. So I think it is perfect. Could you please brief or point out any particulars. Thanks!

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS I don t think this is as automatic.
Besides the report was not working well before: I will test it in our database which contains thousands of lines

**Comment by elicoidal** [comment]
Will be fixed later on in v10.
