### ISSUE TITLE
Set default values at BR creation

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#215]
Set default in BR form view:
* Responsible: should be current user

Set default in BR deliverable form view:
* UoM: should be set to Unit(s) (standard UoM)

Set default in BR Resource lines in Deliverable form view:
* UoM: should be set as followed.
   * Hour(s) if "task" is selected and UoM is empty or 
   * Unit(s) if "procurement" is selected and UoM is empty 
(both standard UoM)

**Comment by martintorresvm** [comment]
@elicoidal Could you create in advance a branch for this topic?
