### ISSUE TITLE
Transifex build is failing

### ISSUE THREAD

**Issue by dreispt** [OCA/business-requirement#22]
Wrong [secret](https://github.com/OCA/maintainer-quality-tools/issues/194#issue-79502151)?

**Comment by elicoidal** [comment]
Hum Probably. Thanks @dreispt 
business-requirement repo doesnot exist though.
@victormartinelicocorp can you have a look

**Comment by martintorresvm** [comment]
@dreispt Surely is easy to fix but I am not experience with Transifex. Could you explain what steps need to do?

**Comment by dreispt** [comment]
@victormartinelicocorp I'm also not inside the OCA/Transifex workings.

**Comment by pedrobaeza** [comment]
Follow these instructions to get the secure word https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L37-L41

**Comment by dreispt** [comment]
@pedrobaeza You need to provide the OCA Transifex password as `your-password`, right?

**Comment by pedrobaeza** [comment]
Yeah, that's right. I have run the script and this is the expected secure:

```
  secure: "SOqfTrrC52vWbjccaSMGEwNlk6wJTQisMzGTwludqbVJ4GdRMZKuqljAzBfmrXqfrM7PVu4ouFeepGgnhhZGVvLTLov2TnSmPhggx369YzAdkxvVAo0Ev6HLi8p8+MwdJbaZRDUPcZ2+Wqn+UuYcZGqp8GU7LHmW0XIQB3n/kq8T69xpBihNEmkMNJvw00fSt71ew1rOjG/JejgOJekVlABp9xf6e+e7pXDPJSAatpaU51+UQkVZvDEPQFoLubyk1HlHOX1MbWshCAmzLCUQuG3FgCOHFnA+GMHRISqeLxvNZ2slk4V5c6BfDIzkOkwtOoYzTzvsuvqXbfs4ZpLNBbOTFN7XzyStkjkcLSPg3Y+zLL+k3kXIrcTpn7lsyP0xpSQAv11qq2nbAstRCW3hIkudoTrUvAYc9FPlFPGomcGkP0lx582ppL4rX/fmxxl3vn/7A+bY4tZ8MwtssMfATQoszUw8sx2/S2mp7/RpiZPdQfve5z95bMt0/BR1UBkzpr5q2zzVqVFV6lQvbmfAK4XZTCONRUX/Ud/TCapC/Cx0xnCe1GF28Ja65uFmAyRwtCcP4kh+wIxYZSB8L2zfVAVNDqnbFy0BjbS3Id8tmwcBDNZUeOM6+amHhs8XP9f/18HR/gFNl0uqxfbfklkOiImYzRp+jTD7MguKrrF26h8="
```
