### ISSUE TITLE
Disable CodeReviewHub

### ISSUE THREAD

**Issue by dreispt** [OCA/business-requirement#23]
It was an experiment, but IMO it is horrible.
Do you agree?

**Comment by elicoidal** [comment]
Yes: I do not use it because I dont have time with so many notifications.
I see the point of it for certain cases or people but not in my case (I monitor probably a hundred repos and react on ping only).
In the same idea I would remove coverall.io

**Comment by dreispt** [comment]
AFAICT it's done.
