### ISSUE TITLE
[brd_project] Improve the naming of smart button titles

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#242]
In BR view, click in smart button "Tasks". In corresponding view the title is "Action Task related BR" (Expected "Tasks").
In BR view, click in smart button "Linked Project". In corresponding view the title is empty (Expected "Projects").

Affects: v8 and v10

**Comment by martintorresvm** [comment]
IMO to be done as well within #241 
@YogeshMahera-SerpentCS?

**Comment by YogeshMahera-SerpentCS** [comment]
@victormartinelicocorp Noted!
