### ISSUE TITLE
Improve and standardize BR groups in user view

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#249]
Here is the current view in the user form view concerning the ACL groups.
![screenshot from 2017-09-18 14-44-04](https://user-images.githubusercontent.com/7600613/30531303-ec4626ec-9c7f-11e7-9f8e-8e504001774f.png)

There are multiple improvements we can make about it:
* The groups BR manager should inherit from BR Stakeholder and this one from BR user and be displayed in a selection box
* The group BR cost should inherit from BR estimation and be displayed in a selection box
* Both selection boxes should be displayed in current subsection (nothing to change)

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS please have a look

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal  Yes

**Comment by elicoidal** [comment]
fixed
