### ISSUE TITLE
In BR the cost control calculation is incorrect

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#253]
Current behavior
summary of the DL/RL:
![screenshot from 2017-09-21 11-04-11](https://user-images.githubusercontent.com/7600613/30677166-b38542cc-9ebc-11e7-80d7-b790041ebf12.png)

In BR the cost control (company currency is CNY):
Currency | EUR
-- | --
Total Revenue | 178,540.65
Total procurement | 3,158.00
Total tasks | 34,960.00
Estimated Gross Profit | 140,422.65

Expected behavior:
- Total revenue is based on the total revenue in the DL
- A new field Total Revenue in company Currency to be added below with the proper currency conversion

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal 
Fixed issue in v8 and v10 #225 and #255

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS this is milestones 10.0
