### ISSUE TITLE
Deliverable lines in the report should follow the order of the sequence

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#254]
Currently deliverable lines in reports are sorted by DB id
Expected: sorted following the DL sequence
NB: should be the same for the RL

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS

**Comment by elicoidal** [comment]
@YogeshMahera-SerpentCS Can you take care of this?

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Yes I am on it
