### ISSUE TITLE
Task page display

### ISSUE THREAD

**Issue by XXXXLM** [OCA/business-requirement#272]
If the task name is too long, the page will be biased to the right.
@elicoidal

**Comment by elicoidal** [comment]
@Miya609 I am not sure there is an easy fix for that. I consider it nice to have for the moment. 

Can you upload a screenshot as example?

**Comment by XXXXLM** [comment]
@elicoidal 
![issue1](https://user-images.githubusercontent.com/33017782/34512461-ae027ad0-f09d-11e7-9668-f7b7ccb8f4d0.png)

**Comment by elicoidal** [comment]
This is an Odoo related bug so closing it. To be reported to the Odoo repo with a proper example
