### ISSUE TITLE
[RFC] New feature: start a quotation directly from BR

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#275]
Current modules allow to start a set of quotation from opportunities. In some cases this is not convenient (for example for single additional BR).

We should add a button in the BR that allows to create a quotation directly from the BR itself (one single quotation from one single BR and children).
Use case (one single BR):
1. User input information in the BR (scope+deliverable+resources)
2. User creates if necessary children BR (optional)
3. User click on the button "Create Quotation" in the BR form view. User confirms the customer (mandatory) in wizard (default is the stakeholder of first BR). A field quotation_id is updated in the BR (in the form view, "other" tab)
4. a quotation is created for the BR and children using the same method as the one in opportunity (adding all deliverables of all BR into the quotation following sequence of BR and deliverable). 
5. Customer, price, currency and other default SO set up should be done the same way as for the opportunity current wizard

Use case (multiple BR):
1. User input information in the BR (scope+deliverable+resources)
2. User creates if necessary children BR (optional)
3. In BR tree view, user select multiple BR and select More/"Create Quotation". BR must be from same stakeholder. User confirms the customer (mandatory) in wizard (default is the stakeholder of first BR). A field quotation_id is updated in the BR (in the form view, "other" tab)
4. a quotation is created for all the BR and their children using the same method as the one in opportunity (adding all deliverables of all BR into the quotation following sequence of BR and deliverable). 
5. Customer, price, currency and other default SO set up should be done the same way as for the opportunity current wizard

**Comment by elicoidal** [comment]
@seb-elico @lonelysun @victormartinelicocorp FYI

**Comment by pedrobaeza** [comment]
Already implemented in deliverables.
