### ISSUE TITLE
Field for_br readonly on wizard view

### ISSUE THREAD

**Issue by andhit-r** [OCA/business-requirement#280]
Hi @elicoidal ,

Is there any reason why field for_br is readonly? https://github.com/OCA/business-requirement/blob/e7247494859dea135a9048e2f6da116a1cda5870/business_requirement_deliverable_project/wizard/generate_projects_view.xml#L21

There are already code to cover when for_br is False https://github.com/OCA/business-requirement/blob/e7247494859dea135a9048e2f6da116a1cda5870/business_requirement_deliverable_project/wizard/generate_projects.py#L68.

I found few case that does not need to create sub project for each br. Can we adapt this use case? I will create a PR if you agree to adapt use case above. Many thanks.

**Comment by elicoidal** [comment]
@andhit-r We originally disabled the function because we didnot need it and didnot have time to develop it (that was at the time we curated the links between projects and BR)
No problem to reactivate it but the creation methods need to be reviewed accordingly
@seb-elico any additional information?

**Comment by seb-elico** [comment]
@elicoidal @andhit-r 
Actually the main reason is that right now, the link between a task and the BR it originated from is coming from the project to which belongs the task which has been generated from the BR. But it appears that there's a link between the task and the resource line, so it's technically possible to find from which BR the task originated by using this task/RL link. If we use the link in such a way, then it won't be necessary to generate systematically a project from the BR and the tasks could be generated directly under the master project. Please note that if I remember correctly, SQL queries of BR earned value report (see #278) and the [Timesheet Activity Report](https://github.com/Elico-Corp/odoo-addons/tree/10.0/timesheet_activity_report) (which ought to be pushed to the OCA BR repo) depend on this project/BR link and would then be impacted.

**Comment by andhit-r** [comment]
@elicoidal @seb-elico thank you for your input. I will look @seb-elico point before i make the modification.
