### ISSUE TITLE
Function of WBS fields

### ISSUE THREAD

**Issue by defcon19** [OCA/business-requirement#289]
When I try Install this module, I see WBS field,
WBS that I know is Work breakdown structure.
Is the same fungction or diferent about WBS in this modules

Regards

**Comment by elicoidal** [comment]
Hi @defcon19 thanks for reporting.
Indeed WBS stands for [Work breakdown structure](https://en.wikipedia.org/wiki/Work_breakdown_structure)
You can specify a [WBS Coding Scheme](https://en.wikipedia.org/wiki/Work_breakdown_structure#Coding_scheme) in the field: it will appear in the list view for easy sorting and in the BR name.

To be noted that there is no automatic WBS numbering.
