### ISSUE TITLE
Duplicated task still linked to the resource line

### ISSUE THREAD

**Issue by seb-elico** [OCA/business-requirement#290]
When a task which have been generated from a resource line is duplicated, it's still linked to that resource line.

This causes issues for reporting purposes, as this task should be considered an un-planned task - e.g. it's the same as if a brand new task had been created and linked to that BR through the project, that would be an un-planned task.

Since the task is linked to the resource line, reporting would virtually increase the total planned time for the BR. For example:

BR contains 1 DL with 2 RL:

- DEV (8h)
- QA (2h)

Project is generated. Reporting would consider that total planned time for this project based on the RL is 10h.

If the DEV task is duplicated, reporting will indicated that total planned time for this project based on the RL is 18h. It's because the DEV RL is counted twice since 2 tasks are linked to it.

Expected behavior:
When a task generated from a BR is duplicated, its link with the RL should be deleted.

CC @elicoidal @victormartinelicocorp

**Comment by JoJoJoJoJoJoJo** [comment]
Not reproduced, in which report can we see the wrong total time? @seb-elico

**Comment by elicoidal** [comment]
@seb-elico

**Comment by seb-elico** [comment]
@Joseph
Project completion report. To be clear, do not modify the report!
------------------
Sébastien Maillard [Chief of Staff]
Phone: +86 186 2103 7589 (Cell), +86 21 6211 8017/27/37 (Office) 
Elico Shanghai (Hong Kong/Shenzhen/Singapore)
Odoo Gold Partner // Best Odoo Partner APAC 2014 and 2016
 

 
 
 
------------------ Original ------------------

**Comment by JoJoJoJoJoJoJo** [comment]
On hold as pr for migration of project_completion_report is not merged.

**Comment by seb-elico** [comment]
@JoJoJoJoJoJoJo to be clear, when a task is duplicated, you need to set the `br_resource_id` to None
