### ISSUE TITLE
[RFC] add a "Step" field in the Resource Lines

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#291]
In order to add a light management of milestones without having a dedicated models, I would like to suggest to add a field Step (Char) in the resources lines that the user can fill in to indicate at which step (or milestone) the resource line (or task) is expected.
* The field should be added to the tree view of the RL
* When the project is created from the RL, the field would be populated to the corresponding task (in specific field (to be added in form and tree view).

Advantage: it allows possible finer classification of the resources necessary for the delivery.

It should be shipped in a specific module depending on `business_requirement_deliverable_project` as it is not necessary to every users.

**Comment by elicoidal** [comment]
cc @seb-elico

**Comment by seb-elico** [comment]
LGTM
