### ISSUE TITLE
Code sprint 2016

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#32]
Link to the etherpad: http://pad.odoo.com/p/BR-codesprint-2016

**Comment by astirpe** [comment]
@elicoidal all the issues we discussed during the Code sprint 2016 were ported from etherpad to github, maybe this issue can be closed, do you agree?

**Comment by elicoidal** [comment]
Agree! thanks @astirpe for the follow-up

I will be under for the next couple of month but will try my best to follow with my own team to finish the migration on v9 and start v10.
