### ISSUE TITLE
[11.0][12.0] Access rights integration with website module

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#321]
Steps to reproduce with any user which has no business requirement and portal groups
Go to menu: website>website>My account

Tested on Runbot 11.0:
```
403: Forbidden
The page you were looking for could not be authorized.
```

On 12.0:
Not yet as no module depends on website on the current migration status but as soon installs website app manually it happens.

**Comment by martintorresvm** [comment]
cc @Tecnativa

**Comment by pedrobaeza** [comment]
Please add the PR with the fix
