### ISSUE TITLE
[RFC] Adding Group By [Parent] in BR

### ISSUE THREAD

**Issue by CBPOforOdoo** [OCA/business-requirement#33]
Need to add Group By [Parent] in the BR tree view to allow users to get their BRs classified by Objectives for example.

**Comment by elicoidal** [comment]
We don't have yet the objective but after discussion we have to add a fields (m2o) "Main category" (below main project) + add a group by/filter feature
@astirpe @mmalorni

**Comment by elicoidal** [comment]
Currently not in the roadmap. Fill free to propose a PR
