### ISSUE TITLE
Resource lines under Deliverables lines tab

### ISSUE THREAD

**Issue by CBPOforOdoo** [OCA/business-requirement#43]
if the Type = "task" and the Root Category for tasks and Assign to columns have values, then if we change the Type to "Procurement" values of the two columns are removed, But; when save and close the Deliverables lines then reopen it we find that the Root Category for tasks and Assign to columns will remain read only but will show their values as if the Type="task" while they should show nothing and being set to Null.

**Comment by astirpe** [comment]
I this this issue could be closed

**Comment by pedrobaeza** [comment]
Yeah, closing
