### ISSUE TITLE
Transfer Fiscal Position when creating a quotation

### ISSUE THREAD

**Issue by mmalorni** [OCA/business-requirement#44]
Correctly copy tax position while creating a quotation from a list of business requirements. Take the fiscal position of the customer set in the Business Requirement record.

**Comment by mmalorni** [comment]
Each line in the quotation doesn't have a tax set.
If the tax is set, the calculation of the tax amount should be done based on the fiscal position of the customer and the product taxes applied. (refresh might be needed but should calculate properly)

**Comment by pedrobaeza** [comment]
Already fixed
