### ISSUE TITLE
Add "Reference" in BR

### ISSUE THREAD

**Issue by CBPOforOdoo** [OCA/business-requirement#45]
Add "Reference" (Text data type) field to the BR and show on the Tree (list) view and adjust issue #37 to show this "Reference" with the description as _**[Reference] Description.**_ instead of [BR Number] Description

**Comment by elicoidal** [comment]
Agree
I would actually use the [BR Number] if [Reference] is false.

**Comment by CBPOforOdoo** [comment]
## More then perfect 👍

Sent from myMail for Android Wednesday, 05 October 2016, 04:16PM +02:00 from Eric Caudal  notifications@github.com :

**Comment by astirpe** [comment]
This issue can be closed, as the PRs #68 and #55 are merged

**Comment by elicoidal** [comment]
:+1:
