### ISSUE TITLE
[RFC] Adding a new Action to show BRs in sequence view

### ISSUE THREAD

**Issue by CBPOforOdoo** [OCA/business-requirement#46]
Create a new menu action under the Business Requirement category menu to show BRs in a sequence view like "Products by Category"  action under Products category menu under Sales root menu to show list of BRs sorted by Parents and "Reference" created in issue #45 .

**Comment by elicoidal** [comment]
Is it sequence view you need or tree view with the parents?
I am not sure you can do both at the same time.

**Comment by CBPOforOdoo** [comment]
What we meant is sorting BRs according to parents then according to the newly added "Reference" field which will allow the user to see BRs grouped by parents then sorted by reference.

## If this is not possible, then sorting the whole list of BRs by reference will be sufficient and most of the job 👍

Sent from myMail for Android Wednesday, 05 October 2016, 04:15PM +02:00 from Eric Caudal  notifications@github.com :

**Comment by elicoidal** [comment]
This covered by new Kanban view #119
