### ISSUE TITLE
Project/Task creation state

### ISSUE THREAD

**Issue by levkar** [OCA/business-requirement#79]
Currently project task creation is possible in approved state. Shouldn't we create tasks after stakeholder approval? What if he doesn't approve?

I am also confused about order of the states.

Current state order: 
Draft -> Confirmed -> Approved -> Stakeholder Approval -> In Progress -> Done

If it's business requirements which is in progress, shouldn't it be before it is being confirmed?
Draft -> In Progress -> Confirmed -> Approved -> Stakeholder Approval -> Done

Maybe I didn't get what is meant by "in progress".

Thanks for the great module by the way.

**Comment by elicoidal** [comment]
Sorry for late reply (I thought I did reply but somewhere it got lost).

> Currently project task creation is possible in approved state. Shouldn't we create tasks after stakeholder approval? What if he doesn't approve?

Project creation should only be available in "stakeholder approval state"
If the stakeholder does not approve there is no need to create the project right?

> I am also confused about order of the states.
Current state order:
Draft -> Confirmed -> Approved -> Stakeholder Approval -> In Progress -> Done
If it's business requirements which is in progress, shouldn't it be before it is being confirmed?
Draft -> In Progress -> Confirmed -> Approved -> Stakeholder Approval -> Done

"In progress" means the project (and tasks from BR) is in progess, not that the BR is been treated

**Comment by elicoidal** [comment]
> Currently project task creation is possible in approved state.

normally not the case anymore. For this reason I close the issue but do not hesitate to reopen if necessary

**Comment by levkar** [comment]
Thanks!
