### ISSUE TITLE
[RFC] Deliverable Lines and Resource Lines independent from BR

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#82]
In order to improve the usability of current view design based form/sub-form/sub-subform we want to switch to a smart button related design where deliverable lines and Resources lines are open via smart buttons

## Business Requirement Model

- partner_id
    - mandatory
- resource_lines
    - o2m business.requirement.resource
    - inverse business_requirement_id  

## Business Requirement Deliverable Model

- business_requirement_id
    - required True

## Business Requirement Resource Model

- business_requirement_id
    - m2o business.requirement
    - required True

## Business Requirement Form

- deliverable_lines should be smart button
- resource_lines create smart button

## Business Requirement Menu

Modify Business Requirement Menu:

    - Possible views (first default): To Kanban View/Tree view/Form/Graph 

    - After Business Requirement add menus:

        - Deliverables
            - Possible views (first default): Kanban View/Tree view/Form/Graph
         - Resources
            - Possible views (first default): Kanban View/Tree view/Form/Graph

## Business Requirement Group by/Search:

- Group by
    - Customer: partner_id
    - Project: project_id
    - Status: state
- Search
    - partner_id
    - project_id
    - state

## Business Requirement Deliverable Group by/Search:

- Group by
    - Business Requirement: business_requirement_id
    - Customer: business_requirement_id.partner_id
    - Project: business_requirement_id.project_id
    - Product: product_id
- Search
    - business_requirement_id
    - business_requirement_id.project_id
    - business_requirement_id.partner_id
    - product_id

## Business Requirement Resource Group by/Search:

- Group by
    - Business Requirement: business_requirement_id
    - Customer: business_requirement_id.partner_id
    - Project: business_requirement_id.project_id
    - Product: product_id
- Search
    - business_requirement_id
    - business_requirement_id.project_id
    - business_requirement_id.partner_id
    - product_id

**Comment by martintorresvm** [comment]
@elicoidal Please have a look

**Comment by elicoidal** [comment]
Made some modifications: I will post in the business requirement group.

**Comment by elicoidal** [comment]
fixed by #113
