### ISSUE TITLE
[RFC] ADD Kanban View on BR model and Form View 

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#85]
Add Kanban view for the main BR menu.

The Kanban frame should contain (similar to task):

    Name+description
    Master Project
    Tags
    Priority (stars)
    # hours in Timesheets (from task related gather the Time spent) / # hours in Resource lines (Time planned on all RL Task Type)
    Tags
    Responsible (Photo)

Links to (similar to project):

    # tasks (to tree view with the Task related)
    # hours (takes to Tree view with all the timesheets on liked task)
    # document (Tree view with all Attachments)

By default, the columns should contain the BR stages.
Sorted by priority + sequence

**Comment by elicoidal** [comment]
fix by #119
