### ISSUE TITLE
[8.0] Followers of the project are not added to the BR

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#90]
Expected is that when creating a new BR from a Master project, the followers from the master project are added to the BR.
Current behavior: no followers are added, only the BR creator.

**Comment by elicoidal** [comment]
@victormartinelicocorp @sudhir-serpentcs

**Comment by sudhir-serpentcs** [comment]
@elicoidal Sure.

**Comment by elicoidal** [comment]
Fixed by #93
