### ISSUE TITLE
[8.0] improve ACL for sales estimation

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#91]
Current behavior
Group "Business Requirement Estimation" is defined in module business-requirement/business_requirement_deliverable_cost/

Expected behavior:

Group "Business Requirement Estimation" is defined in module business-requirement/business_requirement_deliverable/

In tree view following Columns should only be visible for this group in the model and all forms (tree/form):
* unit_price
* price_total
* currency_id

**Comment by martintorresvm** [comment]
@elicoidal the PR https://github.com/OCA/business-requirement/pull/100 regards this issue is almost ready to merge just small changes.
