### ISSUE TITLE
[RFC] Kanban state

### ISSUE THREAD

**Issue by seb-elico** [OCA/business-requirement#99]
It would be great to have a Kanban state on the BR, same way we have it for the tasks.

The standards states should be enough:
- "normal"
- "on hold"
- "ready for next step"

For instance, a BR at stage "Confirmed" with Kanban state "ready for next step" means that it has been estimated and is waiting for approval. Whereas a "normal" one means that the estimation needs to be finalized.

**Comment by seb-elico** [comment]
@elicoidal please confirm

**Comment by elicoidal** [comment]
:+1:

**Comment by YogeshMahera-SerpentCS** [comment]
It means there should be only 3 kanban states as @seb-elico mentioned, right?. But then how should be mapping to the stages should be done with that of the kanban states? Like what knaban state should come under 'Approved' BR stage? 
@elicoidal

**Comment by martintorresvm** [comment]
> It means there should be only 3 kanban states as @seb-elico mentioned, right?. But then how should be mapping to the stages should be done with that of the kanban states? Like what knaban state should come under 'Approved' BR stage?
 
@YogeshMahera-SerpentCS  The meaning in this case is something up to the functional consultant.
So just need to create these kanban states (selection field) regards BR object and display like is done on Task.

**Comment by elicoidal** [comment]
Kanban states are available at any stage (like for the projects).

**Comment by dreispt** [comment]
IMO the best practice is to have dynamic/configurable "Stages", and each stage is mapped to a predefined list of "states". The module default business logic should be tied to the "states", but the en user still has flexibility to tune the actual Stages seen in their Kanban.

The modules [base_kanban_stage](https://github.com/OCA/server-tools/tree/10.0/base_kanban_stage) and [base_kanban_stage_state](https://github.com/OCA/server-tools/tree/10.0/base_kanban_stage_state) already do  all the hard work for you.

**Comment by elicoidal** [comment]
fixed by #119
